import CareerFormModel from "../model/CareerFormModel.js";
import { uploadOnCloudinary } from "../utils/cloudinary.js";
import nodemailer from "nodemailer";

// ⚙️ Create a reusable email transporter once (not every time)
const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT),
    secure: Number(process.env.SMTP_PORT) === 465,
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS, // Use Gmail App Password (not normal Gmail password)
    },
});

// 📧 Universal email sender utility
const sendEmail = async (to, subject, htmlContent) => {
    try {
        const mailOptions = {
            from: `"Career Portal" <${process.env.EMAIL_USER}>`,
            to, // can be a string or comma-separated list
            subject,
            html: htmlContent,
        };

        const info = await transporter.sendMail(mailOptions);
        console.log(`📧 Email sent successfully to: ${to}`);
        return info;
    } catch (error) {
        console.error("❌ Error sending email:", error.message);
        if (error.response) console.error("↳ Gmail response:", error.response);
        throw new Error("Failed to send email");
    }
};

// 🧾 Submit job application
export const submitApplication = async (req, res) => {
    try {
        const { name, email, phoneNo, city, jobApplied } = req.body;

        if (!name || !email || !phoneNo || !city || !jobApplied) {
            return res.status(400).json({ success: false, error: "All fields are required" });
        }

        if (!req.file) {
            return res.status(400).json({ success: false, error: "Resume file is required" });
        }

        console.log("Uploading resume to Cloudinary...");
        const cloudinaryResponse = await uploadOnCloudinary(req.file.path);

        if (!cloudinaryResponse || !cloudinaryResponse.secure_url) {
            return res.status(500).json({ success: false, error: "Failed to upload resume" });
        }

        const resumeUrl = cloudinaryResponse.secure_url;

        const newApplication = await CareerFormModel.create({
            name,
            email,
            phoneNo,
            city,
            jobApplied,
            resume: resumeUrl,
        });

        console.log("✅ Application saved to database:", newApplication._id);

        const adminEmailHTML = `
            <div style="font-family: Arial, sans-serif; color: #333;">
                <h2>📄 New Job Application Received</h2>
                <p><strong>Name:</strong> ${name}</p>
                <p><strong>Email:</strong> ${email}</p>
                <p><strong>Phone:</strong> ${phoneNo}</p>
                <p><strong>City:</strong> ${city}</p>
                <p><strong>Job Applied:</strong> ${jobApplied}</p>
                <p><strong>Resume:</strong> <a href="${resumeUrl}" target="_blank">View Resume</a></p>
                <hr />
                <p style="font-size: 12px; color: #777;">This message was auto-generated by your Career Portal.</p>
            </div>
        `;

        const applicantEmailHTML = `
            <div style="font-family: Arial, sans-serif; color: #333;">
                <h2>Thank you for applying, ${name}!</h2>
                <p>We have received your application for the <strong>${jobApplied}</strong> position.</p>
                <p>Our HR team will review your profile and reach out if your qualifications match our requirements.</p>
                <p>Best wishes,<br/>The HR Team</p>
            </div>
        `;

        try {
            const recipients = `${process.env.HR_EMAIL}, ${process.env.CEO_EMAIL}`;
            await sendEmail(recipients, `New Application - ${name} (${jobApplied})`, adminEmailHTML);
            await sendEmail(email, `Application Received - ${jobApplied}`, applicantEmailHTML);
        } catch (emailError) {
            console.error("⚠️ Email sending failed:", emailError.message);
        }

        res.status(201).json({
            success: true,
            message: "Application submitted successfully",
            data: newApplication,
        });

    } catch (error) {
        console.error("❌ Error Submitting Application:", error.message);
        res.status(500).json({ success: false, error: "Server error while submitting application" });
    }
};

// 📋 Get all applications
export const getAllApplications = async (req, res) => {
    try {
        const applications = await CareerFormModel.find().sort({ createdAt: -1 });
        res.status(200).json({
            success: true,
            count: applications.length,
            data: applications,
        });
    } catch (error) {
        console.error("❌ Error fetching applications:", error.message);
        res.status(500).json({ success: false, error: "Failed to fetch applications" });
    }
};
